[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/ttyUSB0

lib_deps =
    lovyan03/LovyanGFX@^1.2.0
    fischer-simon/Esp32Lua@^5.4.7
