[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/ttyUSB0

lib_deps =
    lovyan03/LovyanGFX@^1.2.0
    fischer-simon/Esp32Lua@^5.4.7

[env:desktop_linux]
platform = native
lib_deps =
    lovyan03/LovyanGFX@^1.2.0
    fischer-simon/Esp32Lua@^5.4.7
build_flags =
    -std=c++17
    -DPLATFORM_LINUX
    -Iinclude
    -Iinclude/hal
    -Iinclude/ui
    -Iinclude/scripting
    -I.pio/libdeps/desktop_linux/Esp32Lua/src
    -lSDL2
    -l:liblua5.4.so.0
build_src_filter =
    +<*>
    -<main.cpp>
