#ifndef SIDESCROLLER_ASSETS_H
#define SIDESCROLLER_ASSETS_H

#include <Arduino.h>

/**
 * Side-Scroller Benchmark Graphic Assets
 * 
 * Includes:
 * 1. Play Surface Dirt & Grass Tileset (32x32)
 * 2. Background Rolling Hills & Trees Tileset (32x32)
 * 3. Army Guy Running Character (8-Frame 16x16 Sprite Sheet)
 * 4. Floating Pickup Gold Star/Gem (16x16 Sprite)
 */

// Helper RGB565 color constants
#define C_TRANS  0x0000 // Transparent Key
#define C_GRASS  0x03E0 // Bright Grass Green
#define C_DIRT1  0x7BE0 // Dirt Brown 1
#define C_DIRT2  0x4A00 // Dirt Brown 2
#define C_DIRT3  0x2900 // Dark Dirt
#define C_HILL1  0x1D26 // Distant Soft Blue-Green
#define C_HILL2  0x2E09 // Distant Hill Green
#define C_TREE1  0x02C0 // Pine Tree Dark Green
#define C_TREE2  0x0400 // Tree Trunk Brown
#define C_SKY    0x1993 // Soft Pastel Sky Blue

#define C_CAMO1  0x3A00 // Army Camo Green
#define C_CAMO2  0x1200 // Dark Army Green
#define C_SKIN   0xFCB0 // Skin Tone
#define C_BOOT   0x18C3 // Dark Boots
#define C_GOLD   0xFFE0 // Gold Pickup
#define C_GOLD2  0xFA20 // Dark Gold

// --- 1. Play Surface Dirt & Grass Tilemap Data (16x10 Grid for 480x320) ---
const int16_t PLAY_SURFACE_MAP[16 * 10] = {
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1
};

// --- 2. Rolling Hills Background Map Data (16x10 Grid) ---
const int16_t HILLS_BACKGROUND_MAP[16 * 10] = {
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1,  3, -1, -1, -1, -1, -1, -1,  3, -1, -1, -1,
    -1, -1, -1,  0,  1,  1,  2, -1, -1, -1,  0,  1,  1,  2, -1, -1,
     0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
};

// --- 3. Play Surface Tileset (32x32 Tiles, 4 Tiles Atlas: Grass Top, Dirt Deep, Stone Block, Empty) ---
const uint16_t DIRT_TILESET_32x32[32 * 32 * 4] PROGMEM = {
    // Tile 0: Grass Top Dirt
    // Generated procedurally in code for crisp 32x32 resolution
};

// --- 4. Floating Pickup Gold Star Sprite (16x16) ---
const uint16_t PICKUP_STAR_16x16[16 * 16] PROGMEM = {
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_GOLD,  C_GOLD,  C_GOLD,  C_GOLD,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_GOLD,  C_GOLD,  C_GOLD2, C_GOLD2, C_GOLD,  C_GOLD,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_GOLD,  C_GOLD,  C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD,  C_GOLD,  C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_GOLD,  C_GOLD,  C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD,  C_GOLD,  C_TRANS, C_TRANS, C_TRANS,
    C_GOLD,  C_GOLD,  C_GOLD,  C_GOLD,  C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD,  C_GOLD,  C_GOLD,  C_GOLD,
    C_GOLD,  C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD,
    C_TRANS, C_GOLD,  C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD,  C_TRANS,
    C_TRANS, C_TRANS, C_GOLD,  C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD,  C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_GOLD,  C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD,  C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_GOLD,  C_GOLD,  C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD,  C_GOLD,  C_TRANS, C_TRANS,
    C_TRANS, C_GOLD,  C_GOLD,  C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD,  C_GOLD,  C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD,  C_GOLD,  C_TRANS,
    C_GOLD,  C_GOLD,  C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_GOLD,  C_GOLD2, C_GOLD2, C_GOLD2, C_GOLD,  C_GOLD,
    C_GOLD,  C_GOLD2, C_GOLD2, C_GOLD,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_GOLD,  C_GOLD2, C_GOLD2, C_GOLD,
    C_GOLD,  C_GOLD,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_GOLD,  C_GOLD,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS
};

// --- 5. Army Guy 8-Frame Running Animation Sprite Sheet (8 Frames of 16x16 = 128x16) ---
const uint16_t ARMY_RUNNER_8FRAMES[16 * 16 * 8] PROGMEM = {
    // Frame 0: Stand Stride
    C_TRANS, C_TRANS, C_TRANS, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_CAMO2, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO2, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_SKIN,  C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_CAMO2, C_CAMO2, C_CAMO2, C_CAMO2, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_CAMO2, C_CAMO2, C_CAMO2, C_CAMO2, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_BOOT,  C_BOOT,  C_BOOT,  C_BOOT,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_BOOT,  C_TRANS, C_TRANS, C_BOOT,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_BOOT,  C_BOOT,  C_TRANS, C_TRANS, C_BOOT,  C_BOOT,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,

    // Frame 1: Stride Right Forward
    C_TRANS, C_TRANS, C_TRANS, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_CAMO2, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO2, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_SKIN,  C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_CAMO2, C_CAMO2, C_CAMO2, C_CAMO2, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_CAMO2, C_CAMO2, C_TRANS, C_TRANS, C_CAMO2, C_CAMO2, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_BOOT,  C_BOOT,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_BOOT,  C_BOOT,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_BOOT,  C_BOOT,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_BOOT,  C_BOOT,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,

    // Frame 2: Stride Mid
    C_TRANS, C_TRANS, C_TRANS, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_CAMO2, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO2, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_SKIN,  C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_CAMO2, C_CAMO2, C_CAMO2, C_CAMO2, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_CAMO2, C_CAMO2, C_CAMO2, C_CAMO2, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_BOOT,  C_BOOT,  C_BOOT,  C_BOOT,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_BOOT,  C_TRANS, C_TRANS, C_BOOT,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_BOOT,  C_BOOT,  C_BOOT,  C_BOOT,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,

    // Frame 3: Stride Left Forward
    C_TRANS, C_TRANS, C_TRANS, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_CAMO2, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO2, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_SKIN,  C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_CAMO2, C_CAMO2, C_CAMO2, C_CAMO2, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_CAMO2, C_CAMO2, C_CAMO2, C_CAMO2, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_BOOT,  C_BOOT,  C_TRANS, C_TRANS, C_BOOT,  C_BOOT,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_BOOT,  C_BOOT,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_BOOT,  C_BOOT,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,

    // Frame 4: High Stride
    C_TRANS, C_TRANS, C_TRANS, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_CAMO2, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO2, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_SKIN,  C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_CAMO2, C_CAMO2, C_CAMO2, C_CAMO2, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_CAMO2, C_CAMO2, C_CAMO2, C_CAMO2, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_BOOT,  C_BOOT,  C_BOOT,  C_TRANS, C_TRANS, C_BOOT,  C_BOOT,  C_BOOT,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,

    // Frame 5: Sprint Stride Right
    C_TRANS, C_TRANS, C_TRANS, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_CAMO2, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO2, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_SKIN,  C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_CAMO2, C_CAMO2, C_CAMO2, C_CAMO2, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_BOOT,  C_BOOT,  C_CAMO2, C_CAMO2, C_CAMO2, C_CAMO2, C_BOOT,  C_BOOT,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_BOOT,  C_BOOT,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_BOOT,  C_BOOT,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,

    // Frame 6: Sprint Mid
    C_TRANS, C_TRANS, C_TRANS, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_CAMO2, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO2, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_SKIN,  C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_CAMO2, C_CAMO2, C_CAMO2, C_CAMO2, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_CAMO2, C_CAMO2, C_CAMO2, C_CAMO2, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_BOOT,  C_BOOT,  C_BOOT,  C_BOOT,  C_BOOT,  C_BOOT,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,

    // Frame 7: Sprint Stride Left
    C_TRANS, C_TRANS, C_TRANS, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_CAMO2, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO2, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_SKIN,  C_CAMO1, C_CAMO1, C_CAMO1, C_CAMO1, C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_CAMO2, C_CAMO2, C_CAMO2, C_CAMO2, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_BOOT,  C_BOOT,  C_CAMO2, C_CAMO2, C_CAMO2, C_CAMO2, C_BOOT,  C_BOOT,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_BOOT,  C_BOOT,  C_BOOT,  C_BOOT,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS
};

#endif // SIDESCROLLER_ASSETS_H
