#ifndef UI_THEME_H
#define UI_THEME_H

#include <LovyanGFX.hpp>

/**
 * UITheme — Visual design token container for the UI framework.
 *
 * A UITheme holds every colour, dimension, and font pointer used by the widget
 * system. Swap the active theme in UIManager to re-skin every widget at once,
 * without touching any widget code.
 *
 * ## Font Pointers
 * Point to any lgfx::IFont-derived font:
 *   - Built-in: &fonts::FreeSans9pt7b, &fonts::FreeSansBold12pt7b, etc.
 *   - Custom:   &MyFont_16pt  (generated by tools/font_converter.py)
 *   - nullptr uses LovyanGFX's built-in default font.
 *
 * ## Colour Format
 * All colours are 16-bit RGB565. Use lgfx::color565(r,g,b) or the
 * GFXContext::color565() helper to generate values.
 */
struct UITheme {
    // --- Palette ---
    uint16_t background;       // Panel / frame fill colour
    uint16_t surface;          // Widget surface (button face, slider track, input bg)
    uint16_t surfacePressed;   // Widget surface when pressed / active
    uint16_t surfaceDisabled;  // Widget surface when disabled
    uint16_t border;           // Default widget border colour
    uint16_t borderFocused;    // Border colour when widget is focused / selected
    uint16_t textPrimary;      // Main label / content text
    uint16_t textSecondary;    // Hint text, value readouts, disabled labels
    uint16_t accent;           // Slider fill, checkbox tick, active indicator
    uint16_t accentDark;       // Darker accent for thumb shadow etc.
    uint16_t danger;           // Destructive-action button tint
    uint16_t titleBar;         // UIFrame title bar background
    uint16_t titleText;        // UIFrame title bar text colour

    // --- Typography ---
    const lgfx::IFont* fontBody;     // Widget labels, option text
    const lgfx::IFont* fontHeading;  // Frame title bar
    const lgfx::IFont* fontMono;     // Numeric value readouts

    // --- Geometry ---
    uint8_t cornerRadius;  // Border-radius for buttons, frames, checkboxes
    uint8_t borderWidth;   // Widget border stroke thickness (px)
    uint8_t paddingX;      // Horizontal internal padding
    uint8_t paddingY;      // Vertical internal padding
    uint8_t spacing;       // Gap between stacked widgets in a UIFrame
    uint8_t checkSize;     // Checkbox / radio indicator size (px)
    uint8_t sliderTrackH;  // Slider track height (px)
    uint8_t sliderThumbR;  // Slider thumb radius (px)
};

// ---------------------------------------------------------------------------
// Built-in Themes
// ---------------------------------------------------------------------------

/**
 * Dark theme — high-contrast dark background, vivid cyan accent.
 * Designed for low-light and gaming contexts.
 */
inline UITheme UITheme_Dark() {
    UITheme t;
    // Palette (all RGB565)
    t.background      = 0x0813;  // Very dark blue-grey
    t.surface         = 0x1A33;  // Dark navy surface
    t.surfacePressed  = 0x2C4F;  // Slightly lighter on press
    t.surfaceDisabled = 0x10A2;  // Muted dark surface
    t.border          = 0x2965;  // Muted steel blue border
    t.borderFocused   = 0x07FF;  // Cyan focused border
    t.textPrimary     = 0xFFFF;  // White
    t.textSecondary   = 0x8410;  // Medium grey
    t.accent          = 0x07FF;  // Cyan
    t.accentDark      = 0x035B;  // Dark cyan
    t.danger          = 0xF800;  // Red
    t.titleBar        = 0x14A4;  // Dark teal title bar
    t.titleText       = 0x07FF;  // Cyan title text

    // Typography — built-in LovyanGFX FreeSans fonts, no extra files needed
    t.fontBody        = &fonts::FreeSans9pt7b;
    t.fontHeading     = &fonts::FreeSansBold12pt7b;
    t.fontMono        = &fonts::FreeMono9pt7b;

    // Geometry
    t.cornerRadius    = 6;
    t.borderWidth     = 1;
    t.paddingX        = 10;
    t.paddingY        = 6;
    t.spacing         = 8;
    t.checkSize       = 20;
    t.sliderTrackH    = 6;
    t.sliderThumbR    = 9;
    return t;
}

/**
 * Light theme — clean white background, deep blue accent.
 * Suitable for educational or productivity-style apps.
 */
inline UITheme UITheme_Light() {
    UITheme t;
    t.background      = 0xF7BE;  // Off-white
    t.surface         = 0xFFFF;  // White widget face
    t.surfacePressed  = 0xC618;  // Light grey pressed
    t.surfaceDisabled = 0xE71C;  // Pale grey disabled
    t.border          = 0xC618;  // Light grey border
    t.borderFocused   = 0x001F;  // Deep blue focused
    t.textPrimary     = 0x0000;  // Black
    t.textSecondary   = 0x8410;  // Medium grey
    t.accent          = 0x001F;  // Deep blue
    t.accentDark      = 0x000D;  // Navy
    t.danger          = 0xF800;  // Red
    t.titleBar        = 0x001F;  // Deep blue title bar
    t.titleText       = 0xFFFF;  // White title text

    t.fontBody        = &fonts::FreeSans9pt7b;
    t.fontHeading     = &fonts::FreeSansBold12pt7b;
    t.fontMono        = &fonts::FreeMono9pt7b;

    t.cornerRadius    = 6;
    t.borderWidth     = 1;
    t.paddingX        = 10;
    t.paddingY        = 6;
    t.spacing         = 8;
    t.checkSize       = 20;
    t.sliderTrackH    = 6;
    t.sliderThumbR    = 9;
    return t;
}

#endif // UI_THEME_H
